# Generated by Django 3.0.5 on 2020-10-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('description', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
