# Generated by Django 3.0.5 on 2020-10-29 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walmart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products',
        ),
    ]
